name: PyInstaller Build

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-22.04
            platform: linux-x86_64
          - os: windows-latest
            platform: windows-amd64
          - os: macos-15-intel
            platform: macos-amd64
          - os: macos-latest
            platform: macos-arm64
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Install Package Manager
        uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
        with:
          enable-cache: true
      - name: Install Python 3.14 (Linux Only)
        if: matrix.os == 'ubuntu-22.04'
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo add-apt-repository ppa:deadsnakes/ppa -y
          sudo apt-get update
          sudo apt-get install -y python3.14-tk libpython3.14
          uv venv .venv --python /usr/bin/python3.14 --seed
      - name: Install Python 3.14 (macOS/Windows)
        if: matrix.os != 'ubuntu-22.04'
        run: uv python install 3.14
      - name: Install Dependencies
        run: uv sync --extra gui --no-dev
      - name: Build PyInstaller Executable
        shell: bash
        run: |
          if [ "${{ matrix.platform }}" = "macos-arm64" ]; then
            export MACOS_ARCH="arm64"
          elif [ "${{ matrix.platform }}" = "macos-amd64" ]; then
            export MACOS_ARCH="x86_64"
          fi
          uv run pyinstaller main.spec --noconfirm
      - name: Generate Desktop Launcher (Linux Only)
        if: matrix.os == 'ubuntu-22.04'
        shell: bash
        run: |
          mv "dist/Jellyfin RPC" dist/jellyfin-rpc
          mkdir -p "dist/Jellyfin RPC"
          mv dist/jellyfin-rpc "dist/Jellyfin RPC/"
          cp images/icon.png "dist/Jellyfin RPC/jellyfin-rpc.png"

          cat << 'EOF' > "dist/Jellyfin RPC/jellyfin-rpc.desktop"
          [Desktop Entry]
          Type=Application
          Version=$(uv version --short)
          Name=Jellyfin RPC
          Comment=Discord Rich Presence for Jellyfin
          Exec=/opt/jellyfin-rpc/jellyfin-rpc
          Icon=/opt/jellyfin-rpc/jellyfin-rpc.png
          Terminal=false
          Categories=Network;Utility;
          StartupWMClass=jellyfin-rpc
          EOF

          cat << 'EOF' > "dist/Jellyfin RPC/install.sh"
          #!/usr/bin/env bash
          set -e

          cd "$(dirname "$0")"
          sudo mkdir -p /opt/jellyfin-rpc
          sudo chmod +x jellyfin-rpc.desktop
          sudo cp jellyfin-rpc.desktop /usr/share/applications/
          sudo cp jellyfin-rpc jellyfin-rpc.png /opt/jellyfin-rpc/
          EOF

          chmod +x "dist/Jellyfin RPC/install.sh"
      - name: Isolate App Bundle (macOS Only)
        if: startsWith(matrix.os, 'macos')
        run: |
          mkdir -p dist/app_bundle
          mv "dist/Jellyfin RPC.app" dist/app_bundle/
      - name: Isolate Windows Binary (Windows Only)
        if: startsWith(matrix.os, 'windows')
        run: |
          mkdir -p "dist/Jellyfin RPC"
          mv "dist/Jellyfin RPC.exe" "dist/Jellyfin RPC/"
      - name: Prepare Artifact Name
        shell: bash
        run: |
          VERSION=$(uv version --short)
          echo "ARTIFACT_NAME=jellyfin-rpc-$VERSION-${{ matrix.platform }}" >> $GITHUB_ENV
      - name: Upload Artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: >-
            ${{ startsWith(matrix.os, 'macos')
                && 'dist/app_bundle/*'
                || 'dist/*' }}
